export {default as arqueiro} from './arqueiro.png'
export {default as atirador} from './atirador.png'
export {default as besta} from './besta.png'
export {default as boneca} from './boneca.png'
export {default as cantora} from './cantora.png'
export {default as cavaleiro} from './cavaleiro.png'
export {default as cleriga} from './cleriga.png'
export {default as espantalho} from './espantalho.png'
export {default as espia} from './espia.png'
export {default as feiticeiro} from './feiticeiro.png'
export {default as ladra} from './ladra.png'
export {default as maga} from './maga.png'
export {default as minotauro} from './minotauro.png'
export {default as monge} from './monge.png'
export {default as ninja} from './ninja.png'
export {default as sereia} from './sereia.png'

